### ISSUE TITLE
Clarify the requirement to build a score "calculator"

### ISSUE THREAD

**Issue by mic-css** [makersacademy/bowling-challenge#214]
Having discussed this with several others in my cohort, many of us were under the impression that we should build a bowling **game**, where the user would click a `roll` button and this would generate a random roll outcome.

I suggest clarifying the requirements to build a score **calculator** that takes user input for rolls and is used as a visual guide. A link to an example, such as [Bowling Genius](http://www.bowlinggenius.com/), might also help.

**Comment by spike01** [comment]
>Count and sum the scores of a bowling game for one player (in JavaScript).

I'd agree, except the point of these challenges is to give students controlled exposure to the kind of problem statements they'll get in tech tests (and then, later on, business requirements). Most of which are hugely open ended, badly specified, and massively unclear.
